### ISSUE TITLE
[TypeError: (0 , n.jsx) is not a function]

### ISSUE THREAD

**Issue by tanerengiiin** [timlrx/contentlayer2#79]
Hello,

I saw the solutions of this error. But when i want to use useMdxComponent in client component, it gives me this error. I have to use it in client component because I created a client SyntaxHighligter. Could you help me please?

**Comment by sanjayc208** [comment]
I am also facing the same issue with 0.5.7 i think the latest version of contentlayer2

**Comment by ohprettyhak** [comment]
@timlrx Could you please help to resolve this issue? I'm experiencing the same problem.

**Comment by tanerengiiin** [comment]
@sanjayc208 this solved my problem. version 5.0.4 is compatible with "use client" @ohprettyhak downgrade your contentlayer2 and next-contentlayer2 versions to 5.0.4

**Comment by Vahor** [comment]
What version of react or next are you using ?

I'm on 
```
contentlayer2@0.5.7
next-contentlayer2@0.5.7
next@15.3.0
react-dom@19.1.0
react@19.1.0
```

I tested on stackblitz with these version and I don't have any issues: https://stackblitz.com/edit/contentlayer2-next15?file=app%2Flib%2Fmdx.tsx

**Comment by sanjayc208** [comment]
@Vahor Correct i think issue is causing because of client components and we cannot avoid in some case. In my understand this has to do everything with release happened after 0.5.5 https://github.com/timlrx/contentlayer2/compare/v0.5.5...main

**Comment by coratgerl** [comment]
Same issue, but works with 0.5.4

**Comment by timlrx** [comment]
Fixed in v0.5.8
